const express=require("express");const axios=require("axios");const crypto=require("crypto");const {upsertDiscordUser}=require("../models/users");const {requireAuth}=require("../middleware/auth");const router=express.Router();
const http=axios.create({timeout:15000,headers:{"User-Agent":"EMS-Majestic-Portal/2.0"}});
const networkCodes=new Set(["ECONNRESET","ETIMEDOUT","ECONNABORTED","EAI_AGAIN","ENETUNREACH","ECONNREFUSED"]);
function networkError(e){return networkCodes.has(e&&e.code)}
function rateLimited(e){const d=e&&e.response&&e.response.data;return e&&e.response&&e.response.status===429||String(d||"").includes("1015")}
function retryAfter(e){const v=Number(e&&e.response&&e.response.headers&&e.response.headers["retry-after"]);return Number.isFinite(v)?Math.max(5,Math.ceil(v)):30}
async function getDiscordUser(token){let last;for(let i=0;i<3;i++){try{return await http.get("https://discord.com/api/users/@me",{headers:{Authorization:"Bearer "+token}})}catch(e){last=e;if(!(networkError(e)||rateLimited(e))||i===2)throw e;await new Promise(r=>setTimeout(r,rateLimited(e)?retryAfter(e)*1000:700*(i+1)));}}throw last}
router.get("/discord",(req,res)=>{if(req.session.oauthStartedAt&&Date.now()-req.session.oauthStartedAt<5000)return res.status(429).render("error",{status:429,title:"Слишком частые попытки",message:"Подождите несколько секунд и повторите вход."});const state=crypto.randomBytes(24).toString("hex");req.session.oauthState=state;req.session.oauthStartedAt=Date.now();const params=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,redirect_uri:process.env.DISCORD_REDIRECT_URI,response_type:"code",scope:"identify",state});res.redirect("https://discord.com/oauth2/authorize?"+params)});
router.get("/callback",async(req,res)=>{if(req.query.error)return res.status(400).render("error",{status:400,title:"Вход отменён",message:"Discord не предоставил разрешение на вход."});if(!req.query.code||!req.query.state||req.query.state!==req.session.oauthState)return res.status(400).render("error",{status:400,title:"Некорректный вход",message:"Сессия авторизации устарела или не прошла проверку безопасности."});delete req.session.oauthState;try{const token=await http.post("https://discord.com/api/oauth2/token",new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,client_secret:process.env.DISCORD_CLIENT_SECRET,grant_type:"authorization_code",code:req.query.code,redirect_uri:process.env.DISCORD_REDIRECT_URI}).toString(),{headers:{"Content-Type":"application/x-www-form-urlencoded"}});const profile=(await getDiscordUser(token.data.access_token)).data;const coreUser=await upsertDiscordUser(profile);req.session.user=profile;req.session.coreUser=coreUser;const target=typeof req.session.returnTo==="string"&&req.session.returnTo.startsWith("/")&&!req.session.returnTo.startsWith("//")?req.session.returnTo:"/dashboard";delete req.session.returnTo;req.session.save(e=>e?res.status(500).render("error",{status:500,title:"Ошибка сессии",message:"Не удалось сохранить вход."}):res.redirect(target));}catch(e){console.error("Discord OAuth failed:",e.response&&e.response.status,e.code||"",rateLimited(e)?"rate_limited":"");if(rateLimited(e))return res.status(429).render("error",{status:429,title:"Discord временно ограничил запросы",message:"Подождите около "+retryAfter(e)+" секунд и начните вход заново."});res.status(502).render("error",{status:502,title:"Не удалось войти через Discord",message:networkError(e)?"Соединение с Discord было прервано. Попробуйте позже.":"Discord отклонил запрос авторизации."});}});
router.get("/logout",(req,res)=>req.session.destroy(()=>{res.clearCookie("ems.sid");res.redirect("/")}));
router.get("/resignation",requireAuth,(req,res)=>res.render("resignation",{user:req.session.user,success:false,error:null}));
router.post("/resignation",requireAuth,async(req,res)=>{const {characterInfo,rank,reason,activeReprimand}=req.body||{};if(!characterInfo||!reason||!activeReprimand)return res.status(400).render("resignation",{user:req.session.user,success:false,error:"Заполните все обязательные поля."});const webhookUrl=process.env.RESIGNATION_WEBHOOK_URL,roleId=process.env.RESIGNATION_ROLE_ID;if(!webhookUrl||!roleId)return res.status(500).render("resignation",{user:req.session.user,success:false,error:"Webhook заявления не настроен."});try{await axios.post(webhookUrl,{username:"EMS | Отдел кадров",content:"<@&"+roleId+">",allowed_mentions:{roles:[roleId]},embeds:[{title:"Заявление на увольнение",color:15548997,timestamp:new Date().toISOString(),author:{name:req.session.user.global_name||req.session.user.username||"Discord"},fields:[{name:"Discord",value:"<@"+req.session.user.id+">",inline:true},{name:"Фамилия Имя | Статик",value:String(characterInfo).slice(0,1024)},{name:"Ранг",value:String(rank||"Не указан").slice(0,1024),inline:true},{name:"Активный выговор",value:String(activeReprimand).slice(0,1024),inline:true},{name:"Причина",value:String(reason).slice(0,1024)}]}]},{timeout:10000});res.render("resignation",{user:req.session.user,success:true,error:null});}catch(e){res.status(502).render("resignation",{user:req.session.user,success:false,error:"Не удалось отправить заявление в Discord."});}});
module.exports=router;